version: "3.9"
services:
  reactjs:
    container_name: merquelio-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: serve -s dist -p 3000

networks:
  default:
    name: merquelio-network
